import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Card from '../../components/Card';
import MetricCard from '../../components/MetricCard';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Users, UserCheck, AlertTriangle } from 'lucide-react';
const segmentData = [
    { segment: 'New Customers', count: 156, satisfaction: 92, loyalty: 65 },
    { segment: 'Loyal Customers', count: 234, satisfaction: 96, loyalty: 94 },
    { segment: 'At-Risk', count: 42, satisfaction: 58, loyalty: 25 },
];
const customerJourney = [
    { stage: 'Awareness', sentiment: 7.2, count: 450 },
    { stage: 'Consideration', sentiment: 7.8, count: 320 },
    { stage: 'Purchase', sentiment: 8.5, count: 280 },
    { stage: 'Post-Purchase', sentiment: 8.7, count: 240 },
    { stage: 'Retention', sentiment: 8.2, count: 190 },
];
export default function CustomerInsights() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-bold text-gray-900 mb-2", children: "Customer Insights" }), _jsx("p", { className: "text-gray-600", children: "Deep understanding of customer behavior and preferences" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsx(MetricCard, { title: "Total Customers", value: "432", change: "\u2191 15% this month", changeType: "positive", icon: Users, backgroundColor: "bg-blue-50" }), _jsx(MetricCard, { title: "Retention Rate", value: "87%", change: "\u2191 5% improvement", changeType: "positive", icon: UserCheck, backgroundColor: "bg-green-50" }), _jsx(MetricCard, { title: "At-Risk Customers", value: "42", change: "\u2193 8 fewer from last month", changeType: "positive", icon: AlertTriangle, backgroundColor: "bg-red-50" })] }), _jsx(Card, { title: "Customer Segments Analysis", subtitle: "Breakdown by customer type", children: _jsx("div", { className: "space-y-4", children: segmentData.map((item, index) => (_jsxs("div", { className: "p-4 bg-gray-50 rounded-lg border border-gray-200", children: [_jsxs("div", { className: "flex justify-between items-start mb-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-semibold text-gray-900", children: item.segment }), _jsxs("p", { className: "text-sm text-gray-600", children: [item.count, " customers"] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-2xl font-bold text-gray-900", children: [item.satisfaction, "%"] }), _jsx("p", { className: "text-xs text-gray-600", children: "Satisfaction" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: "text-gray-600", children: "Loyalty Score" }), _jsxs("span", { className: "font-semibold text-gray-900", children: [item.loyalty, "%"] })] }), _jsx("div", { className: "w-full bg-gray-300 rounded-full h-2", children: _jsx("div", { className: `h-2 rounded-full ${item.loyalty > 80 ? 'bg-green-500' : item.loyalty > 50 ? 'bg-yellow-500' : 'bg-red-500'}`, style: { width: `${item.loyalty}%` } }) })] })] }, index))) }) }), _jsx(Card, { title: "Customer Journey Sentiment", subtitle: "Sentiment across purchase journey", children: _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(BarChart, { data: customerJourney, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#e5e7eb" }), _jsx(XAxis, { dataKey: "stage" }), _jsx(YAxis, {}), _jsx(Tooltip, {}), _jsx(Legend, {}), _jsx(Bar, { dataKey: "sentiment", fill: "#3B82F6", name: "Avg Sentiment" })] }) }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Card, { title: "Top Customer Needs", subtitle: "Most requested features/services", children: _jsx("div", { className: "space-y-3", children: [
                                { need: 'Faster delivery', priority: 'High', mentions: 156 },
                                { need: 'More customization', priority: 'High', mentions: 134 },
                                { need: 'Better customer support', priority: 'Medium', mentions: 98 },
                                { need: 'Eco-friendly options', priority: 'Medium', mentions: 76 },
                                { need: 'Mobile app', priority: 'Low', mentions: 42 },
                            ].map((item, index) => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-gray-50 rounded-lg", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: item.need }), _jsx("span", { className: `text-xs px-2 py-1 rounded-full mt-1 inline-block ${item.priority === 'High' ? 'bg-red-100 text-red-800' :
                                                    item.priority === 'Medium' ? 'bg-yellow-100 text-yellow-800' :
                                                        'bg-gray-100 text-gray-800'}`, children: item.priority })] }), _jsx("span", { className: "text-sm font-semibold text-gray-900", children: item.mentions })] }, index))) }) }), _jsx(Card, { title: "Customer Satisfaction Drivers", subtitle: "What makes customers happy", children: _jsx("div", { className: "space-y-3", children: [
                                { driver: 'Quality of service', impact: 95 },
                                { driver: 'Response time', impact: 87 },
                                { driver: 'Staff friendliness', impact: 92 },
                                { driver: 'Value for money', impact: 78 },
                                { driver: 'Consistency', impact: 85 },
                            ].map((item, index) => (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { className: "font-medium text-gray-900", children: item.driver }), _jsxs("span", { className: "text-gray-700", children: [item.impact, "%"] })] }), _jsx("div", { className: "w-full bg-gray-200 rounded-full h-2", children: _jsx("div", { className: "bg-green-500 h-2 rounded-full", style: { width: `${item.impact}%` } }) })] }, index))) }) })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg p-6 border border-gray-200 shadow-sm", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Customer Lifetime Value" }), _jsx("p", { className: "text-3xl font-bold text-gray-900", children: "$4,250" }), _jsx("p", { className: "text-xs text-gray-600 mt-2", children: "Average per customer" })] }), _jsxs("div", { className: "bg-white rounded-lg p-6 border border-gray-200 shadow-sm", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Churn Risk Score" }), _jsx("p", { className: "text-3xl font-bold text-green-600", children: "Low" }), _jsx("p", { className: "text-xs text-gray-600 mt-2", children: "9.7% at-risk" })] }), _jsxs("div", { className: "bg-white rounded-lg p-6 border border-gray-200 shadow-sm", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Expansion Opportunity" }), _jsx("p", { className: "text-3xl font-bold text-gray-900", children: "$1.2M" }), _jsx("p", { className: "text-xs text-blue-600 mt-2", children: "Potential upsell value" })] }), _jsxs("div", { className: "bg-white rounded-lg p-6 border border-gray-200 shadow-sm", children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Customer Effort Score" }), _jsx("p", { className: "text-3xl font-bold text-gray-900", children: "3.2/5" }), _jsx("p", { className: "text-xs text-gray-600 mt-2", children: "Low effort (better)" })] })] })] }));
}
