import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Card from '../../components/Card';
import MetricCard from '../../components/MetricCard';
import { TrendingUp, AlertTriangle } from 'lucide-react';
export default function Predictive() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-bold text-gray-900 mb-2", children: "Predictive Analytics" }), _jsx("p", { className: "text-gray-600", children: "Forecast trends and anticipate customer needs" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(MetricCard, { title: "Next Month Forecast", value: "~315 reviews", change: "\u2191 Based on current trend", changeType: "positive", icon: TrendingUp, backgroundColor: "bg-blue-50" }), _jsx(MetricCard, { title: "Churn Risk Alert", value: "42 customers", change: "\u2191 5 new at-risk", changeType: "negative", icon: AlertTriangle, backgroundColor: "bg-red-50" })] }), _jsx(Card, { title: "Rating Forecast", subtitle: "Predicted rating for next 3 months", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "p-4 bg-green-50 rounded-lg border border-green-200", children: [_jsx("p", { className: "font-semibold text-green-900", children: "July Forecast" }), _jsx("p", { className: "text-3xl font-bold text-green-600 mt-2", children: "4.85 \u2605" }), _jsx("p", { className: "text-sm text-green-800 mt-1", children: "\u2191 0.05 improvement expected" })] }), _jsxs("div", { className: "p-4 bg-green-50 rounded-lg border border-green-200", children: [_jsx("p", { className: "font-semibold text-green-900", children: "August Forecast" }), _jsx("p", { className: "text-3xl font-bold text-green-600 mt-2", children: "4.87 \u2605" }), _jsx("p", { className: "text-sm text-green-800 mt-1", children: "\u2191 0.02 improvement expected" })] }), _jsxs("div", { className: "p-4 bg-blue-50 rounded-lg border border-blue-200", children: [_jsx("p", { className: "font-semibold text-blue-900", children: "September Forecast" }), _jsx("p", { className: "text-3xl font-bold text-blue-600 mt-2", children: "4.82 \u2605" }), _jsx("p", { className: "text-sm text-blue-800 mt-1", children: "\u2193 Slight seasonal dip expected" })] })] }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Card, { title: "Churn Risk Score", subtitle: "Customers likely to leave", children: _jsx("div", { className: "space-y-3", children: [
                                { name: 'Sarah Mitchell', risk: 85, reason: 'Negative review trend' },
                                { name: 'James Anderson', risk: 72, reason: 'Reduced engagement' },
                                { name: 'Emily Watson', risk: 68, reason: 'Price sensitivity' },
                                { name: 'David Brown', risk: 61, reason: 'Long response time' },
                            ].map((item, index) => (_jsxs("div", { className: "p-3 bg-gray-50 rounded-lg border border-gray-200", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("span", { className: "font-medium text-gray-900", children: item.name }), _jsxs("span", { className: `px-3 py-1 rounded-full text-sm font-bold ${item.risk > 75 ? 'bg-red-100 text-red-800' :
                                                    item.risk > 60 ? 'bg-yellow-100 text-yellow-800' :
                                                        'bg-orange-100 text-orange-800'}`, children: [item.risk, "%"] })] }), _jsx("p", { className: "text-xs text-gray-600", children: item.reason })] }, index))) }) }), _jsx(Card, { title: "Growth Opportunity", subtitle: "Expansion potential", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "p-4 bg-green-50 rounded-lg border border-green-200", children: [_jsx("p", { className: "font-semibold text-green-900", children: "Upsell Potential" }), _jsx("p", { className: "text-2xl font-bold text-green-600 mt-2", children: "$1.2M" }), _jsx("p", { className: "text-sm text-green-800 mt-1", children: "156 customers likely to upgrade" })] }), _jsxs("div", { className: "p-4 bg-blue-50 rounded-lg border border-blue-200", children: [_jsx("p", { className: "font-semibold text-blue-900", children: "Cross-sell Potential" }), _jsx("p", { className: "text-2xl font-bold text-blue-600 mt-2", children: "$850K" }), _jsx("p", { className: "text-sm text-blue-800 mt-1", children: "234 customers interested" })] }), _jsxs("div", { className: "p-4 bg-purple-50 rounded-lg border border-purple-200", children: [_jsx("p", { className: "font-semibold text-purple-900", children: "Retention Value" }), _jsx("p", { className: "text-2xl font-bold text-purple-600 mt-2", children: "$2.1M" }), _jsx("p", { className: "text-sm text-purple-800 mt-1", children: "Save from churn prevention" })] })] }) })] }), _jsx(Card, { title: "Recommended Actions", subtitle: "AI-powered recommendations", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "p-4 bg-red-50 border border-red-200 rounded-lg", children: [_jsx("p", { className: "font-semibold text-red-900", children: "\uD83D\uDEA8 URGENT: Reach out to Sarah Mitchell" }), _jsx("p", { className: "text-sm text-red-800 mt-1", children: "High churn risk (85%) - Schedule immediate call to resolve concerns" })] }), _jsxs("div", { className: "p-4 bg-yellow-50 border border-yellow-200 rounded-lg", children: [_jsx("p", { className: "font-semibold text-yellow-900", children: "\u2192 Start upsell campaign" }), _jsx("p", { className: "text-sm text-yellow-800 mt-1", children: "Target 156 loyal customers with premium tier offer" })] }), _jsxs("div", { className: "p-4 bg-green-50 border border-green-200 rounded-lg", children: [_jsx("p", { className: "font-semibold text-green-900", children: "\u2713 Maintain quality standards" }), _jsx("p", { className: "text-sm text-green-800 mt-1", children: "Current satisfaction is excellent - focus on consistency" })] })] }) })] }));
}
